//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jiuhuan.plan {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("home.png")]
        public string image_home {
            get {
                return ((string)(this["image_home"]));
            }
            set {
                this["image_home"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logo.ico")]
        public string icon_logo {
            get {
                return ((string)(this["icon_logo"]));
            }
            set {
                this["icon_logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.209")]
        public string database_server {
            get {
                return ((string)(this["database_server"]));
            }
            set {
                this["database_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string database_user {
            get {
                return ((string)(this["database_user"]));
            }
            set {
                this["database_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hao123.com")]
        public string database_password {
            get {
                return ((string)(this["database_password"]));
            }
            set {
                this["database_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("plan")]
        public string database_name {
            get {
                return ((string)(this["database_name"]));
            }
            set {
                this["database_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int database_timeout {
            get {
                return ((int)(this["database_timeout"]));
            }
            set {
                this["database_timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int database_reconnect_time {
            get {
                return ((int)(this["database_reconnect_time"]));
            }
            set {
                this["database_reconnect_time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT TEAM_CODE AS FCode,TEAM_DESCRIPTION AS FName,TEAM_CAPACITY AS FCapacity,TE" +
            "AM_RATIO AS FRatio,REMARK AS FRemark FROM CQJH.dbo.MACHINE_TEAM")]
        public string sql_machine_team_findall {
            get {
                return ((string)(this["sql_machine_team_findall"]));
            }
            set {
                this["sql_machine_team_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int task_helper_interval_default {
            get {
                return ((int)(this["task_helper_interval_default"]));
            }
            set {
                this["task_helper_interval_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int log_upload_interval {
            get {
                return ((int)(this["log_upload_interval"]));
            }
            set {
                this["log_upload_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Workday")]
        public string sql_workday_findall {
            get {
                return ((string)(this["sql_workday_findall"]));
            }
            set {
                this["sql_workday_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE Workday")]
        public string sql_workday_deleteall {
            get {
                return ((string)(this["sql_workday_deleteall"]));
            }
            set {
                this["sql_workday_deleteall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT m1.DOC_NO as FBillNo,m1.DOC_DATE as FDate,i1.ITEM_CODE as FNumber,i1.ITEM_NAME as FName,i1.ITEM_SPECIFICATION as FModel
, CASE WHEN m1.STATUS = '1' THEN '未生产'
	   WHEN m1.STATUS = '2' THEN '已发料'
	   WHEN m1.STATUS = '3' THEN '生产中'
  END AS FState
,MIS.是否缺料 AS FLack                  --是否缺料
,PLAN_QTY as FQty
,COMPLETED_QTY as FCompletedQty           --完工数量
,SCRAP_QTY as FScrapQty                   --报废数量
,XRECEIPT_SETS as FReceiptQty             --退料数量
,PLAN_START_DATE as FPlanStartDate        --计划开工
,PLAN_COMPLETE_DATE as FPlanCompletedDate --计划完工
,m1.REMARK as FRemark
FROM CQJH.dbo.MO m1
INNER JOIN CQJH.dbo.ITEM i1 ON m1.ITEM_ID=i1.ITEM_BUSINESS_ID
LEFT JOIN v_MoInventoryStatus MIS ON m1.DOC_NO = MIS.工单号
WHERE 1=1
AND m1.RELEASE_FLAG=1         --下达
AND m1.STATUS IN ('1','2','3')   --1：未生产；2：已发料；3：生产中
AND m1.PLAN_COMPLETE_DATE >= '{0}' AND m1.PLAN_COMPLETE_DATE <= '{1}'")]
        public string sql_mo_findall {
            get {
                return ((string)(this["sql_mo_findall"]));
            }
            set {
                this["sql_mo_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT WORK_CENTER_CODE,WORK_CENTER_NAME FROM CQJH.dbo.WORK_CENTER")]
        public string sql_work_center_findall {
            get {
                return ((string)(this["sql_work_center_findall"]));
            }
            set {
                this["sql_work_center_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from v_operation_findall_by_mo where FBillNo in ({0})")]
        public string v_operation_findall_by_mo {
            get {
                return ((string)(this["v_operation_findall_by_mo"]));
            }
            set {
                this["v_operation_findall_by_mo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_ScheduleRecord WHERE 1=1")]
        public string v_schedule_record_findall {
            get {
                return ((string)(this["v_schedule_record_findall"]));
            }
            set {
                this["v_schedule_record_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_OperationRecord WHERE 1=1")]
        public string v_operation_record_findall {
            get {
                return ((string)(this["v_operation_record_findall"]));
            }
            set {
                this["v_operation_record_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_ScheduleDetailsRecord WHERE 1=1")]
        public string v_schedule_details_record_findall {
            get {
                return ((string)(this["v_schedule_details_record_findall"]));
            }
            set {
                this["v_schedule_details_record_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM [User] WHERE FName=\'{0}\' AND FPassword=\'{1}\'")]
        public string sql_user_name_password {
            get {
                return ((string)(this["sql_user_name_password"]));
            }
            set {
                this["sql_user_name_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_ScheduleFinalRecord WHERE 1=1")]
        public string v_schedule_final_record_findall {
            get {
                return ((string)(this["v_schedule_final_record_findall"]));
            }
            set {
                this["v_schedule_final_record_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_schedule_final_findall_by_mo where FBillNo in ({0})")]
        public string v_schedule_final_findall_by_mo {
            get {
                return ((string)(this["v_schedule_final_findall_by_mo"]));
            }
            set {
                this["v_schedule_final_findall_by_mo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE ScheduleFinalRecord\r\nWHERE 1=1\r\nAND FOperationPlanStartDate>=\'{0}\' AND FOp" +
            "erationPlanStartDate<=\'{1}\'\r\nAND FUser = \'{2}\'\r\nAND FClasses LIKE \'%{3}%\'")]
        public string sql_schedule_final_record_deleteall {
            get {
                return ((string)(this["sql_schedule_final_record_deleteall"]));
            }
            set {
                this["sql_schedule_final_record_deleteall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from v_MoInventoryStatus_D where FBillNo = \'{0}\' AND FInventoryStatus<>\'" +
            "充足\'")]
        public string v_MoInventoryStatus_D_find_by_mo {
            get {
                return ((string)(this["v_MoInventoryStatus_D_find_by_mo"]));
            }
            set {
                this["v_MoInventoryStatus_D_find_by_mo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT ITEM_CODE AS MaterialCode, CAST(REQUIRED_QTY AS decimal(18,3)) AS Quantity" +
            "\r\nFROM [CQJH].dbo.MO_D\r\nINNER JOIN [CQJH].dbo.ITEM ON MO_D.ITEM_ID = ITEM.ITEM_B" +
            "USINESS_ID\r\nINNER JOIN [CQJH].dbo.MO ON MO_D.MO_ID = MO.MO_ID\r\nWHERE MO.DOC_NO =" +
            " \'{0}\'")]
        public string sql_mo_d_find_by_billno {
            get {
                return ((string)(this["sql_mo_d_find_by_billno"]));
            }
            set {
                this["sql_mo_d_find_by_billno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM v_StockAvailableQuantity")]
        public string v_StockAvailableQuantity_findall {
            get {
                return ((string)(this["v_StockAvailableQuantity_findall"]));
            }
            set {
                this["v_StockAvailableQuantity_findall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM coc.dbo.StampRecordSilianData WHERE 1=1")]
        public string sql_stamp_record_silian_data_findall {
            get {
                return ((string)(this["sql_stamp_record_silian_data_findall"]));
            }
            set {
                this["sql_stamp_record_silian_data_findall"] = value;
            }
        }
    }
}
